-- Websites generated by the builder.
create table "site" (
  "id" text not null primary key,
  "userId" text not null references "user" ("id") on delete cascade,
  "prompt" text not null,
  "title" text,
  "html" text,
  "status" text not null,
  "error" text,
  "createdAt" integer not null,
  "updatedAt" integer not null
);
create index "site_userId_createdAt_idx" on "site" ("userId", "createdAt");
